import { RoundButton } from "@/components/RoundButton";
import { useAuth } from "@/auth/AuthContext";
import { Text, View, Image, Platform } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import * as React from 'react';
import { encodeBase64 } from "@/encryption/base64";
import { authGetToken } from "@/auth/authGetToken";
import { router, useRouter } from "expo-router";
import { StyleSheet, useUnistyles } from "react-native-unistyles";
import { getRandomBytesAsync } from "expo-crypto";
import { useIsLandscape } from "@/utils/responsive";
import { Typography } from "@/constants/Typography";
import { trackAccountCreated, trackAccountRestored } from '@/track';
import { HomeHeaderNotAuth } from "@/components/HomeHeader";
import { MainView } from "@/components/MainView";
import { t } from '@/text';
import { Modal } from '@/modal';
import axios from 'axios';
import * as Clipboard from 'expo-clipboard';
import { getServerUrl } from '@/sync/serverConfig';
import { log } from '@/log';
import { describeNetworkError } from '@/utils/networkDiagnostics';

export default function Home() {
    const auth = useAuth();
    if (!auth.isAuthenticated) {
        return <NotAuthenticated />;
    }
    return (
        <Authenticated />
    )
}

function Authenticated() {
    return <MainView variant="phone" />;
}

function NotAuthenticated() {
    const { theme } = useUnistyles();
    const auth = useAuth();
    const router = useRouter();
    const isLandscape = useIsLandscape();
    const insets = useSafeAreaInsets();
    const [lastAccountError, setLastAccountError] = React.useState<string | null>(null);

    const getAccountDiagnostics = React.useCallback(() => {
        return log.getLogs()
            .filter((entry) => entry.includes('[ACCOUNT') || entry.includes('[AUTH]'))
            .slice(-80);
    }, []);

    const copyAccountDiagnostics = React.useCallback(async () => {
        const diagnostics = getAccountDiagnostics();
        await Clipboard.setStringAsync(diagnostics.length > 0 ? diagnostics.join('\n') : 'No account diagnostics captured.');
        Modal.alert('已复制', '诊断日志已复制，可以直接发给我。');
    }, [getAccountDiagnostics]);

    const probeServerHealth = React.useCallback(async (requestId: string) => {
        const serverUrl = getServerUrl();
        log.log(`[ACCOUNT ${requestId}] health GET ${serverUrl}/health`);
        const response = await axios.get(`${serverUrl}/health`, { timeout: 8000 });
        log.log(`[ACCOUNT ${requestId}] health status=${response.status}`);
    }, []);

    const createAccount = async () => {
        const requestId = Date.now().toString(36);
        const serverUrl = getServerUrl();
        setLastAccountError(null);
        log.log(`[ACCOUNT ${requestId}] createAccount tapped platform=${Platform.OS} server=${serverUrl}`);
        try {
            const secret = await getRandomBytesAsync(32);
            log.log(`[ACCOUNT ${requestId}] secret generated bytes=${secret.length}`);
            await probeServerHealth(requestId);
            const token = await authGetToken(secret);
            log.log(`[ACCOUNT ${requestId}] token result=${typeof token === 'string' ? 'present' : 'missing'}`);
            if (token && secret) {
                await auth.login(token, encodeBase64(secret, 'base64url'));
                log.log(`[ACCOUNT ${requestId}] login saved`);
                trackAccountCreated();
            } else {
                throw new Error('Auth token missing');
            }
        } catch (error) {
            console.error('Error creating account', error);
            const detail = describeNetworkError(error);
            log.log(`[ACCOUNT ${requestId}] failed ${detail}`);
            setLastAccountError(detail);
            Modal.alert(
                '创建账户失败',
                `诊断信息：${detail}\n\n请点页面下方“复制诊断日志”，把复制出来的内容发给我。`
            );
        }
    }

    const diagnosticsPanel = lastAccountError ? (
        <View style={styles.diagnosticsContainer}>
            <Text style={styles.diagnosticsTitle}>创建账户失败</Text>
            <Text style={styles.diagnosticsText} selectable={true}>{lastAccountError}</Text>
            <RoundButton
                size="small"
                title="复制诊断日志"
                action={copyAccountDiagnostics}
                display="inverted"
            />
        </View>
    ) : null;

    const portraitLayout = (
        <View style={styles.portraitContainer}>
            <Image
                source={theme.dark ? require('@/assets/images/logotype-light.png') : require('@/assets/images/logotype-dark.png')}
                resizeMode="contain"
                style={styles.logo}
            />
            <Text style={styles.title}>
                {t('welcome.title')}
            </Text>
            <Text style={styles.subtitle}>
                {t('welcome.subtitle')}
            </Text>
            {Platform.OS !== 'android' && Platform.OS !== 'ios' ? (
                <>
                    <View style={styles.buttonContainer}>
                        <RoundButton
                            title={t('welcome.loginWithMobileApp')}
                            onPress={() => {
                                trackAccountRestored();
                                router.push('/restore');
                            }}
                        />
                    </View>
                    <View style={styles.buttonContainerSecondary}>
                        <RoundButton
                            size="normal"
                            title={t('welcome.createAccount')}
                            action={createAccount}
                            display="inverted"
                        />
                    </View>
                </>
            ) : (
                <>
                    <View style={styles.buttonContainer}>
                        <RoundButton
                            title={t('welcome.createAccount')}
                            action={createAccount}
                        />
                    </View>
                    <View style={styles.buttonContainerSecondary}>
                        <RoundButton
                            size="normal"
                            title={t('welcome.linkOrRestoreAccount')}
                            onPress={() => {
                                trackAccountRestored();
                                router.push('/restore');
                            }}
                            display="inverted"
                        />
                    </View>
                    {diagnosticsPanel}
                </>
            )}
        </View>
    );

    const landscapeLayout = (
        <View style={[styles.landscapeContainer, { paddingBottom: insets.bottom + 24 }]}>
            <View style={styles.landscapeInner}>
                <View style={styles.landscapeLogoSection}>
                    <Image
                        source={theme.dark ? require('@/assets/images/logotype-light.png') : require('@/assets/images/logotype-dark.png')}
                        resizeMode="contain"
                        style={styles.logo}
                    />
                </View>
                <View style={styles.landscapeContentSection}>
                    <Text style={styles.landscapeTitle}>
                        {t('welcome.title')}
                    </Text>
                    <Text style={styles.landscapeSubtitle}>
                        {t('welcome.subtitle')}
                    </Text>
                    {Platform.OS !== 'android' && Platform.OS !== 'ios'
                        ? (<>
                            <View style={styles.landscapeButtonContainer}>
                                <RoundButton
                                    title={t('welcome.loginWithMobileApp')}
                                    onPress={() => {
                                        trackAccountRestored();
                                        router.push('/restore');
                                    }}
                                />
                            </View>
                            <View style={styles.landscapeButtonContainerSecondary}>
                                <RoundButton
                                    size="normal"
                                    title={t('welcome.createAccount')}
                                    action={createAccount}
                                    display="inverted"
                                />
                            </View>
                        </>)
                        : (<>
                            <View style={styles.landscapeButtonContainer}>
                                <RoundButton
                                    title={t('welcome.createAccount')}
                                    action={createAccount}
                                />
                            </View>
                            <View style={styles.landscapeButtonContainerSecondary}>
                                <RoundButton
                                    size="normal"
                                    title={t('welcome.linkOrRestoreAccount')}
                                    onPress={() => {
                                        trackAccountRestored();
                                        router.push('/restore');
                                    }}
                                    display="inverted"
                                />
                            </View>
                            {diagnosticsPanel}
                        </>)
                    }
                </View>
            </View>
        </View>
    );

    return (
        <>
            <HomeHeaderNotAuth />
            {isLandscape ? landscapeLayout : portraitLayout}
        </>
    )
}

const styles = StyleSheet.create((theme) => ({
    // NotAuthenticated styles
    portraitContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    logo: {
        width: 300,
        height: 90,
    },
    title: {
        marginTop: 16,
        textAlign: 'center',
        fontSize: 24,
        ...Typography.default('semiBold'),
        color: theme.colors.text,
    },
    subtitle: {
        ...Typography.default(),
        fontSize: 18,
        color: theme.colors.textSecondary,
        marginTop: 16,
        textAlign: 'center',
        marginHorizontal: 24,
        marginBottom: 64,
    },
    buttonContainer: {
        maxWidth: 280,
        width: '100%',
        marginBottom: 16,
    },
    buttonContainerSecondary: {
    },
    // Landscape styles
    landscapeContainer: {
        flexBasis: 0,
        flexGrow: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 48,
    },
    landscapeInner: {
        flexGrow: 1,
        flexBasis: 0,
        maxWidth: 800,
        flexDirection: 'row',
    },
    landscapeLogoSection: {
        flexBasis: 0,
        flexGrow: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingRight: 24,
    },
    landscapeContentSection: {
        flexBasis: 0,
        flexGrow: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingLeft: 24,
    },
    landscapeTitle: {
        textAlign: 'center',
        fontSize: 24,
        ...Typography.default('semiBold'),
        color: theme.colors.text,
    },
    landscapeSubtitle: {
        ...Typography.default(),
        fontSize: 18,
        color: theme.colors.textSecondary,
        marginTop: 16,
        textAlign: 'center',
        marginBottom: 32,
        paddingHorizontal: 16,
    },
    landscapeButtonContainer: {
        width: 280,
        marginBottom: 16,
    },
    landscapeButtonContainerSecondary: {
        width: 280,
    },
    diagnosticsContainer: {
        marginTop: 12,
        width: 320,
        maxWidth: '88%',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: theme.colors.surfaceHigh,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        gap: 8,
    },
    diagnosticsTitle: {
        ...Typography.default('semiBold'),
        color: theme.colors.text,
        fontSize: 14,
    },
    diagnosticsText: {
        ...Typography.default(),
        color: theme.colors.textSecondary,
        fontSize: 12,
        lineHeight: 16,
    },
}));
