**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!.npmrc

!patches/
!patches/**

!packages/
!packages/happy-server/
!packages/happy-server/**
!packages/happy-wire/
!packages/happy-wire/**

!Dockerfile.server.slim
