import { describe, expect, it, vi } from 'vitest';
import { CheckpointRetentionSchedule } from './checkpointRetentionSchedule';
describe('checkpoint retention schedule', () => {
    it('checks startup at idle then daily; retries failures after an hour, prevents overlaps, drains on stop', async () => {
        let idle = false;
        let now = 0;
        const collect = vi.fn(async () => undefined);
        const schedule = new CheckpointRetentionSchedule({ collect, isIdle: () => idle, now: () => now, onError: vi.fn() });
        await schedule.tick();
        expect(collect).not.toHaveBeenCalled();
        idle = true;
        await schedule.tick();
        expect(collect).toHaveBeenCalledTimes(1);
        now = 86400_000 - 1;
        await schedule.tick();
        expect(collect).toHaveBeenCalledTimes(1);
        now++;
        idle = false;
        await schedule.tick();
        expect(collect).toHaveBeenCalledTimes(1);
        idle = true;
        collect.mockRejectedValueOnce(new Error('collection failed'));
        await schedule.tick();
        await schedule.tick();
        now += 3600_000 - 1;
        await schedule.tick();
        expect(collect).toHaveBeenCalledTimes(2);
        now++;
        await schedule.tick();
        expect(collect).toHaveBeenCalledTimes(3);
        let release!: () => void;
        collect.mockImplementationOnce(() => new Promise<undefined>(resolve => { release = () => resolve(undefined); }));
        now += 86400_000;
        const running = schedule.tick();
        await schedule.tick();
        expect(collect).toHaveBeenCalledTimes(4);
        let stopped = false;
        const stopping = schedule.stop().then(() => { stopped = true; });
        await Promise.resolve();
        expect(stopped).toBe(false);
        release();
        await Promise.all([running, stopping]);
        now += 86400_000;
        await schedule.tick();
        expect(collect).toHaveBeenCalledTimes(4);
    });
});
