import { Avatar as DiceBearAvatar, Style } from '@dicebear/core';
import adventurerNeutral from '@dicebear/styles/adventurer-neutral.json';

/*
 * The face a new bot is given, drawn from a seed. Mirrors the desktop's BotFace.
 *
 * Every face is DiceBear's Adventurer Neutral: eyes, brows and a mouth on a solid
 * ground, no head, no hair. It is a remix of Lisa Wischofsky's pack of the same
 * name (CC BY 4.0), chosen because a bot is a colleague rather than a user
 * account: an expression, not a portrait.
 *
 * A face is a pure function of its seed. Nothing is fetched and nothing is
 * generated by a model: the style definition and the renderer are bundled, so
 * the same seed draws the same face offline, in a test, and on the daemon once
 * it has been painted and put on the bot.
 */

/** The one style this module draws, built once and reused for every face. */
const style = new Style(adventurerNeutral as ConstructorParameters<typeof Style>[0]);

/** Who drew the pack, read from the style definition so a pack update carries its own credit. */
export const botFaceCredit = {
    pack: adventurerNeutral.meta.source.name,
    artist: adventurerNeutral.meta.creator.name,
    artistUrl: adventurerNeutral.meta.creator.url,
} as const;

/** One of the four faces offered for a new bot, by position. */
export type BotFaceSlot = 0 | 1 | 2 | 3;

/** The four faces rolled together for a new bot. Each is a seed; the picture is derived. */
export type BotFaceSeeds = readonly [string, string, string, string];

/**
 * Four fresh face seeds. Eight base-36 characters is far more faces than there
 * are bots, and short enough to read in a debug snapshot.
 */
export function rollBotFaceSeeds(): BotFaceSeeds {
    const one = () => Math.random().toString(36).slice(2, 10).padEnd(8, '0');
    return [one(), one(), one(), one()];
}

/**
 * The SVG markup for a seed, at the given pixel size.
 *
 * DiceBear embeds an RDF `<metadata>` block and an XML comment that neither
 * native renderer needs; they are stripped so the markup is only drawing.
 */
export function botFaceSvg(seed: string, size: number): string {
    return new DiceBearAvatar(style, { seed, size })
        .toString()
        .replace(/<!--[\s\S]*?-->/g, '')
        .replace(/<metadata[\s\S]*?<\/metadata>/g, '');
}

/** The raster the daemon keeps: 256px is more than any face is shown at. */
export const BOT_FACE_PAINT_SIZE = 256;
