/**
 * Builds a review prompt that instructs the agent to fetch and review PR changes itself.
 * The agent runs in the worktree and has full filesystem + tool access.
 */

export function buildReviewPrompt(prUrl: string, branchName: string, agent: 'claude' | 'codex' | 'gemini'): string {
    const agentLabel = agent === 'claude' ? 'Claude' : agent === 'codex' ? 'Codex' : 'Gemini';
    return `You are performing a code review on a pull request.

PR URL: ${prUrl}
Branch: ${branchName}

## Instructions

1. First, run \`gh pr diff '${branchName}'\` to get the full diff of this PR. If that fails, determine the base branch by running \`git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@'\`, then use \`git diff origin/<base>...HEAD\`.

2. Read through the diff carefully. For any non-trivial changes, use your tools to read the full file context around the changed code — don't review the diff in isolation.

3. Provide your review with these sections:

**Summary** — What does this PR do? (2-3 sentences)

**Issues Found** — Bugs, logic errors, edge cases, or incorrect behavior. For each issue:
- Reference the specific file and line
- Explain WHY it's a problem
- Suggest a fix

**Code Quality** — Naming, structure, duplication, readability concerns.

**Security** — Any injection, auth, data exposure, or OWASP concerns. Say "None found" if clean.

**Suggestions** — Non-blocking improvements that would make the code better.

4. After completing your review, post it as a comment on the GitHub PR by running:
\`gh pr comment '${branchName}' --body '<your review>'\`
Format the comment body in GitHub-flavored markdown. Start the comment with this header:
\`> **AI Code Review** — generated by ${agentLabel}\`
Then include all sections from step 3.

## Guidelines

- Be specific. Always reference file paths and line numbers.
- Check that changed functions are called correctly by their callers — read the callers if needed.
- Look for missing error handling, edge cases, and off-by-one errors.
- If tests should exist for the changes, note their absence.
- Be constructive — explain the "why" behind every comment.
- Don't comment on style preferences or formatting if they follow the existing codebase conventions.`;
}
