import { beforeAll, afterAll, it, expect } from 'vitest';
import nacl from 'tweetnacl';
import { randomBytes } from 'node:crypto';
import { createTestDatabase } from './testDatabase';
import { createAIServiceStore } from './store';
import { createServiceGrants, serviceDigest, sealServiceEnvelope } from './grants';
import type { ServiceGrantScope } from '@slopus/happy-wire';
let ctx:Awaited<ReturnType<typeof createTestDatabase>>, store:ReturnType<typeof createAIServiceStore>, grants:ReturnType<typeof createServiceGrants>, scope:ServiceGrantScope;
const machineKeys=nacl.box.keyPair();
beforeAll(async()=>{
 ctx=await createTestDatabase(); const db=ctx.database;
 await db.account.create({ data:{ id:'grants-owner',publicKey:'grants-owner' } });
 await db.machine.create({ data:{ id:'grants-machine',accountId:'grants-owner',metadata:'sealed' } });
 await db.codexAccountProfile.create({ data:{ id:'grants-profile',accountId:'grants-owner',displayName:'One',externalAccountFingerprint:'one',credential:Buffer.from('sealed') } });
 store=createAIServiceStore(db); grants=createServiceGrants(db,store);
 const target={ machineId:'grants-machine',engine:'codex' as const,accountRef:{ kind:'codex-profile' as const,id:'grants-profile' } };
 const service=await store.createService('grants-owner',{ name:'A',config:{ ...target,modelId:null,reasoning:{ mode:'default' } } });
 scope={ appId:'relationship-advisor',serviceId:service.id,targets:[target],permissions:['chat'],expiresAt:null };
 await db.appChatWorker.create({ data:{ machineId:target.machineId,accountId:'grants-owner',protocol:3,serviceProtocol:'ai-services/1',servicePublicKey:Buffer.from(machineKeys.publicKey).toString('base64'),activeUntil:new Date(Date.now()+60000) } });
},120000);
afterAll(async()=>{ await ctx.database.$disconnect(); await ctx.pg.close(); });
it('returns platform secrets once, stores only digest and per-machine sealed keys, rejects browser origins',async()=>{
 const receipt=await grants.issueServiceGrant('grants-owner',scope.appId,scope.serviceId,scope);
 expect((await grants.authenticate(receipt.credential)).kind).toBe('platform-grant');
 await expect(grants.authenticate(receipt.credential,'https://advisor.paws.rodeo')).rejects.toMatchObject({ code:'permission-denied' });
 const row=await ctx.database.aIServiceAuthorization.findUniqueOrThrow({ where:{ id:receipt.id } });
 expect(JSON.stringify(row)).not.toContain(receipt.messageKey); expect(JSON.stringify(row)).not.toContain(receipt.credential);
 const bundle=Buffer.from((row.machineEnvelopes as Record<string,string>)['grants-machine'],'base64');
 const opened=nacl.box.open(bundle.subarray(56),bundle.subarray(32,56),bundle.subarray(0,32),machineKeys.secretKey)!;
 expect(JSON.parse(Buffer.from(opened).toString()).messageKey).toBe(receipt.messageKey);
 expect(await store.listServiceAuthorizations('grants-owner',scope.serviceId)).not.toHaveProperty('credential');
 await store.revokeAuthorization('grants-owner',receipt.id);
 await expect(grants.authenticate(receipt.credential)).rejects.toMatchObject({ code:'authorization-revoked' });
});
it('keeps personal keys sealed with retryable exact-secret redemption and registered origins',async()=>{
 const browser=nacl.box.keyPair(),verifier=randomBytes(32).toString('base64url'),credential=randomBytes(32).toString('base64url');
 const origin='https://advisor.paws.rodeo';
 const pairing=await grants.createPersonalPairing(scope.appId,origin,Buffer.from(browser.publicKey).toString('base64'),serviceDigest(verifier));
 const messageKey=randomBytes(32).toString('base64');
 const appEnvelope=sealServiceEnvelope({ protocol:'ai-services/1',messageKey,grantId:pairing.id },Buffer.from(browser.publicKey).toString('base64'));
 const machineEnvelope=sealServiceEnvelope({ protocol:'ai-services/1',messageKey,grantId:pairing.id },Buffer.from(machineKeys.publicKey).toString('base64'));
 await grants.approvePersonalPairing('grants-owner',pairing.id,scope,appEnvelope,{ 'grants-machine':machineEnvelope });
 const first=await grants.redeemPersonalPairing(pairing.id,origin,verifier,credential);
 expect(first).toEqual(await grants.redeemPersonalPairing(pairing.id,origin,verifier,credential));
 expect(JSON.stringify(first)).not.toContain(messageKey);
 await expect(grants.redeemPersonalPairing(pairing.id,origin,verifier,randomBytes(32).toString('base64url'))).rejects.toMatchObject({ code:'permission-denied' });
 const token=`paws_service.${pairing.id}.${credential}`;
 expect((await grants.authenticate(token,origin)).kind).toBe('personal-grant');
 await expect(grants.authenticate(token,'https://advisor.paws.rodeo.evil')).rejects.toMatchObject({ code:'permission-denied' });
 await expect(grants.authenticate(token)).rejects.toMatchObject({ code:'permission-denied' });
 const row=await ctx.database.aIServiceAuthorization.findUniqueOrThrow({ where:{ id:pairing.id } });
 expect(JSON.stringify(row)).not.toContain(messageKey);
});
it('loads immutable business prompts for a second app and rejects unknown revisions',async()=>{
 await store.registerBusinessPrompt({ id:'summarizer',version:'1' },'Summarize the supplied text in one sentence.');
 await store.registerApplication({ appId:'summary-app',name:'Summary',origins:['https://summary.example'],capabilities:['chat'],businessPrompt:{ id:'summarizer',version:'1' } });
 expect(await store.resolveBusinessPrompt((await store.readApplication('summary-app')).businessPrompt)).toBe('Summarize the supplied text in one sentence.');
 expect(await store.resolveBusinessPrompt({ id:'summarizer',version:'2' })).toBeNull();
 await expect(ctx.database.aIServiceBusinessPrompt.update({ where:{ id_version:{ id:'summarizer',version:'1' } },data:{ body:'Mutated' } })).rejects.toThrow();
});
