/**
 * Codex Session Fork
 *
 * Fork and truncate Codex CLI's native JSONL session files for the duplicate feature.
 * Codex stores sessions at ~/.codex/sessions/{yyyy}/{mm}/{dd}/rollout-{datetime}-{conversationId}.jsonl
 *
 * Unlike Gemini (where Happy manages the JSONL files and uses Happy session IDs as filenames),
 * Codex fork returns a file path — the Codex CLI uses file paths for its native resumeConversation RPC.
 */

import { randomUUID } from 'node:crypto';
import { copyFile, readFile, writeFile, unlink as unlinkAsync } from 'node:fs/promises';
import { dirname, join, basename } from 'node:path';
import { logger } from '@/ui/logger';
import { findCodexSessionFile, generateStableUuid, extractUserText, isSystemMessage } from './codexSessionReader';

export interface CodexForkResult {
  success: boolean;
  /** Absolute path to the new forked JSONL file */
  newFilePath?: string;
  errorMessage?: string;
}

/**
 * Fork a Codex session without truncation.
 * Copies the JSONL file to a new file with a fresh UUID in the same directory.
 */
export async function forkCodexSession(codexSessionId: string): Promise<CodexForkResult> {
  return forkAndTruncateCodexSession(codexSessionId);
}

/**
 * Fork a Codex session and optionally truncate at a specific UUID.
 *
 * The UUID is a stable hash generated by codexSessionReader (codex:{timestamp}:{index}).
 * To truncate, we re-count user messages during copy to find the matching one.
 */
export async function forkAndTruncateCodexSession(
  codexSessionId: string,
  truncateBeforeUuid?: string,
): Promise<CodexForkResult> {
  const originalPath = findCodexSessionFile(codexSessionId);
  if (!originalPath) {
    return { success: false, errorMessage: `Codex session file not found for: ${codexSessionId}` };
  }

  // Generate new filename in the same directory
  const dir = dirname(originalPath);
  const now = new Date();
  const dateStr = now.toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const newUUID = randomUUID();
  const newPath = join(dir, `rollout-${dateStr}-${newUUID}.jsonl`);

  try {
    if (!truncateBeforeUuid) {
      // Simple copy — no truncation
      await copyFile(originalPath, newPath);
    } else {
      // Copy with truncation: keep lines before the user message matching the UUID
      const content = await readFile(originalPath, 'utf-8');
      const lines = content.split('\n');
      const outputLines: string[] = [];
      let userIndex = 0;
      let foundTruncationPoint = false;

      for (const line of lines) {
        if (!line.trim()) continue;
        if (foundTruncationPoint) continue;

        try {
          const parsed = JSON.parse(line);

          // Check if this is the user message we want to truncate at
          if (parsed.type === 'response_item' && parsed.payload?.role === 'user') {
            const text = extractUserText(parsed.payload);
            if (text && !isSystemMessage(text)) {
              const timestamp = parsed.timestamp || '';
              const uuid = generateStableUuid(timestamp, userIndex);
              if (uuid === truncateBeforeUuid) {
                foundTruncationPoint = true;
                continue;
              }
              userIndex++;
            }
          }
        } catch { /* keep line anyway */ }

        if (!foundTruncationPoint) {
          outputLines.push(line);
        }
      }

      await writeFile(newPath, outputLines.join('\n') + '\n', 'utf-8');
    }

    logger.debug(`[CodexSessionFork] Forked ${basename(originalPath)} -> ${basename(newPath)}`);
    return { success: true, newFilePath: newPath };
  } catch (error) {
    try { await unlinkAsync(newPath); } catch { /* ignore */ }
    return {
      success: false,
      errorMessage: error instanceof Error ? error.message : 'Failed to fork Codex session',
    };
  }
}
