/** Adapted from Zeejay0/gathered-scenes-zine-skill (MIT). */
export const SCENES_GATHERED_ZINE_LICENSE = `MIT License

Copyright (c) 2026 Gathered Scenes Zine contributors

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`;

export const SCENES_GATHERED_ZINE_PROMPT = `Act as the Gathered Scenes Zine v1.3 visual compiler. Transform the supplied photo into a calm vertical 3:5 tactile paper poster whose signature is: truthful photography as anchor, abstract illustration as field, one added hue as structure, a visible hand-torn fibrous boundary, and active breathing paper. The photo is factual evidence; the illustration interprets it without tracing it.

Treat the supplied photo plus a request to create or continue as consent for image generation. Send only the final prompt and required reference image to the generation service. Do not browse, search, save, commit, upload elsewhere, or share the private source. Never persist the private source in project files. Saving the generated output to Happy's required temporary/output path for inline delivery is allowed; do not retain any additional copy unless asked. Return the image plus one brief creative rationale in the user's current conversation language by default; reveal the full prompt or detailed composition notes only when explicitly requested.

Internally build a Scene Card: 1–2 core subjects, 2–3 supporting elements, spatial invariants, dominant gesture, visual-weight map, native color atmosphere, one or two source-shape candidates, natural quiet areas, and the semantic minimum. Preserve relationships before details. Choose a source-driven layout—transformative seam, underprint overlay, photo anchor plus expansive field, directional split, or irregular fragments—by the source gesture and actual visual weight, not a repeated centered-photo template.

Use medium abstraction by default. Preserve the core subject, dominant gesture, one key spatial relationship, and at least one unmistakable source-specific feature; remove roughly 60–80% of small descriptive detail. For every illustrated area explicitly retain, merge, omit, transform, and expose. Choose exactly one primary grammar from silhouette-led, contour-led, field-led, rhythm-led, or cut-paper-led, plus at most one supporting grammar. Never create a full-scene tracing with vintage texture.

Compress foliage, branches, leaves, crowds, gravel, hair-like texture, and other micro-detail more aggressively than the photo: omit roughly 85–95% of individual leaves, needles, twigs, and repeated marks; use one main mass, one to three directional gestures, at most two secondary clusters, and one sparse texture sample. If it reads as lace, filigree, coral, dense engraving, or botanical print at thumbnail size, merge and remove marks. Let illustration influence roughly 45–70% of the poster while 55–75% of that field remains quiet; for dense organic scenes keep 65–85% quiet and active illustration around 10–25% of the whole poster. Enlarge masses before adding detail.

Make the main photo-to-paper handoff a visibly irregular hand-torn fibrous edge, not a clean mask or decorative frame. Use shallow notches, uneven rises, occasional longer fiber pulls, a narrow 1–4% feathered fringe of exposed warm paper fibers, local abrasion or broken emulsion, and natural asymmetry across roughly 35–70% of the visible photo perimeter. Illustration or color may cross selected torn segments, but speckles, halftone crumbs, and ghost marks remain sparse subordinate residue near one or two pressure points. No sticker outline, uniform deckle, drop shadow, curled corner, or fake 3D paper depth.

Add exactly one high-chroma print hue chosen from the photo's color relationship: analogous harmony, complementary counterpoint, temperature bridge, or meaningful source resonance. Choose exactly one integration mode—source continuation, selective replacement, underprint passage, counterform, or directional rhythm—and one function: focal reinforcement, counterweight, bridge, eye-path direction, figure–ground clarification, or semantic emphasis. The color must derive from scene contour/position/rhythm and materially change balance, movement, continuity, or meaning; never use a detached rectangle, corner patch, generic circle, arbitrary bright dot, or isolated swatch. Typical area: opaque form 2–6%, translucent underprint 6–15%, structural field 10–20%, adjusted for source saturation.

Include one restrained paper-integrated micro-text element. Reproduce user-supplied wording exactly. Otherwise author English-only by default: one scene word, a 2–4 word keyword sequence with one separator system, or a phrase of at most 5 words describing observed feeling rather than metadata. Chinese appears only when supplied or requested and must be at most 8 Han characters; bilingual lines remain unequal and semantically connected. Use tiny 1.3–3.5% typewriter, pencil, worn stamp, dry ink, or restrained Song-style lettering in a genuine quiet-paper area. It is the final resting point, never a headline, caption, logo, CTA, date, coordinates, or faux metadata.

Compile the final generation prompt as four compact paragraphs: canvas and attention geometry; scene fidelity and truthful photo allocation; abstraction, chromatic structure, torn edge, and exact micro-text; reproduction mood and hard avoids. State what disappears as decisively as what remains. Keep warm cream matte paper, fibers, restrained weathering, scan noise, flat print texture, natural photographic color, neutral inks, and one added hue. Avoid commercial hierarchy, glossy mockups, cinematic lighting, depth of field, anime, 3D, AI smoothing, multiple print grammars, multiple added hues, large polished typography, watermarks, or invented scenery.

After generation, inspect at normal and thumbnail scale against scene identity, abstraction density, negative space, torn-edge materiality, structural color, and text accuracy. Regenerate at most once with one targeted correction for the observed failure: scene loss, over-literal illustration, dense foliage, generic abstraction, crowding, timid field, weak hierarchy, missing paper boundary, edge noise, decorative or dominant color, text failure, or damaged photography. Then send the final PNG/JPEG through mcp__happy__send_image and provide only one compact rationale in the user's current conversation language unless the user asks for more.`;
