import { it, expect } from 'vitest';
import { createAIServiceClient } from './client';
import { createNodePlatformTransport } from './nodePlatformTransport';
import { createPlatformServiceHandler } from './nodePlatformHandler';
import { createBrowserPlatformTransport } from './platformTransport';
import { createMemoryServiceStorage } from './storage';
import { binding, fixture, makeReceipt } from './testFixtures';
it('requires host login and conversation ownership before every upstream bridge action', async () => {
    const upstream = fixture(), node = createAIServiceClient({ appId: 'advisor', transport: createNodePlatformTransport({ appId: 'advisor', receipt: makeReceipt('platform-grant'), serverUrl: 'https://paws.test', storage: createMemoryServiceStorage(), fetch: upstream.fetcher }) });
    const handler = createPlatformServiceHandler(node, { authorize: async (operation, context: {
            user: string;
        }) => context.user === 'owner' && (!operation.bindingId || operation.bindingId === 'binding'), registerConversation: async () => { }, resolveBinding: async () => binding });
    const denied = await handler({ method: 'GET', path: '/bindings/binding/turns/turn' }, { user: 'other' });
    expect(denied.status).toBe(403);
    expect(upstream.requests).toHaveLength(0);
    const smuggled = await handler({ method: 'POST', path: '/bindings/binding/turns', body: { requestId: 'request', messages: [{ role: 'user', text: 'hello' }], subject: 'owner' } }, { user: 'other' });
    expect(smuggled.status).not.toBe(200);
    expect(upstream.requests).toHaveLength(0);
    const bridgeFetch: typeof fetch = async (url, init) => { const requestUrl = new URL(String(url)); expect(requestUrl.origin).toBe('https://app.test'); expect(new Headers(init?.headers).has('authorization')).toBe(false); expect(init?.credentials).toBe('same-origin'); const result = await handler({ method: init?.method ?? 'GET', path: requestUrl.pathname.replace('/api/ai', ''), body: init?.body ? JSON.parse(String(init.body)) : undefined, signal: init?.signal ?? undefined }, { user: 'owner' }); return Response.json(result.body, { status: result.status, headers: result.headers }); };
    const browser = createAIServiceClient({ appId: 'advisor', transport: createBrowserPlatformTransport({ appId: 'advisor', baseUrl: '/api/ai', origin: 'https://app.test', storage: createMemoryServiceStorage(), fetch: bridgeFetch }) });
    const connection = await browser.connections.authorize();
    expect(Object.keys(connection)).not.toContain('messageKey');
    const bound = await browser.conversations.create();
    expect(bound).toEqual(binding);
    await expect(browser.turns.start({ binding: bound, requestId: 'request', messages: [{ role: 'user', text: 'hello' }] })).rejects.toMatchObject({ code: 'transport-error', requestId: 'request' });
    const restored = await browser.turns.start({ binding: bound, requestId: 'request', messages: [{ role: 'user', text: 'hello' }] });
    expect(restored.record.id).toBe('turn');
    expect(upstream.posts).toBe(1);
    expect((await browser.turns.read({ bindingId: 'binding', turnId: 'turn' })).text).toBe('answer');
    browser.dispose();
    node.dispose();
});
it('refuses a cross-origin application bridge', () => expect(() => createBrowserPlatformTransport({ appId: 'advisor', baseUrl: 'https://foreign.test', origin: 'https://app.test', storage: createMemoryServiceStorage() })).toThrow());
